
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePDF = async (elementId, data) => {
    const element = document.getElementById(elementId);
    if (!element) return;

    const canvas = await html2canvas(element, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');

    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    // Add Header
    pdf.setFontSize(20);
    pdf.setTextColor(40, 40, 40);
    pdf.text("EV Battery Health Report", 15, 20);

    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Date: ${new Date().toLocaleString()}`, 15, 28);
    pdf.text(`Vehicle ID: ${data.battery_type} | Dist: ${data.total_dist_km}km`, 15, 33);

    // Add Dashboard Screenshot
    pdf.addImage(imgData, 'PNG', 0, 40, pdfWidth, pdfHeight);

    // Add Analysis Summary Text
    // Add Analysis Summary Text
    let yPos = 40 + pdfHeight + 10;

    pdf.setFontSize(14);
    pdf.setTextColor(0, 0, 0);
    pdf.text("Analysis Summary", 15, yPos);
    yPos += 8;

    pdf.setFontSize(11);
    pdf.setTextColor(60, 60, 60);
    const summaryLines = [
        `Calculated SOH: ${data.predicted_soh.toFixed(2)}%`,
        `Degradation Rate: ${data.degradation_rate.toFixed(2)}%`,
        `Anomaly Detected: ${data.anomaly_warning ? 'YES - Attention Required' : 'No - Normal Operation'}`,
        '',
        'AI Assessment:',
        data.anomaly_warning
            ? 'The system detected irregular degradation patterns. This suggests the battery is aging faster than expected for this mileage. Recommended Action: Service check-up and thermal system inspection.'
            : 'The battery is performing within expected parameters. degradation is consistent with usage history. Continue standard maintenance schedule.'
    ];

    summaryLines.forEach(line => {
        pdf.text(line, 15, yPos);
        yPos += 7;
    });

    // --- PAGE 2: TECHNICAL APPENDIX ---
    pdf.addPage();

    // Header
    pdf.setFontSize(18);
    pdf.setTextColor(0, 128, 128); // Teal
    pdf.text("Technical Methodology & Formulas", 15, 20);

    // 1. SOH Model
    let y = 35;
    const addSection = (title, content) => {
        pdf.setFontSize(12);
        pdf.setTextColor(0, 0, 0);
        pdf.text(title, 15, y);
        y += 7;

        pdf.setFontSize(10);
        pdf.setTextColor(80, 80, 80);
        const lines = pdf.splitTextToSize(content, 180);
        pdf.text(lines, 15, y);
        y += (lines.length * 5) + 8;
    };

    addSection("1. Hybrid State of Health (SOH) Model",
        "Our system uses a Two-Stage Knowledge Distillation architecture fused with Physics-Guided Regularization. \n" +
        "Formula: Final_SOH = 100 - [(AI_Model_Pred * 0.4) + (Physics_Decay * 0.6)]\n" +
        "- AI Model: Random Forest Regressor trained on NASA Battery Dataset (Randomized usage patterns).\n" +
        "- Physics Decay: A theoretical floor calculated as: (Mileage/1000 * 0.15%) + (Cycles/100 * 0.5%). This ensures the model respects physical laws of electrochemical aging."
    );

    addSection("2. Resale Value Estimation",
        "Based on 'Market Depreciation' curves for used EVs (Source: Kelley Blue Book trends). \n" +
        "Formula: Value = Base_Price ($45k) * Mileage_Factor * SOH_Penalty\n" +
        "- Mileage Factor: Depreciates 10% for every 20,000km.\n" +
        "- SOH Penalty: Quadratic drop ((SOH/100)^2). A 90% health battery retains ~81% value, while 70% health drops to ~49% value."
    );

    addSection("3. Material Composition Analysis",
        "Derived from Argonne National Laboratory's BatPaC (Battery Performance and Cost) Model. \n" +
        "We map the specific chemistry (NMC vs LFP) to its elemental mass:\n" +
        "- NMC (Standard): High Nickel (~470g/kWh), Cobalt (~130g/kWh), Lithium (~90g/kWh).\n" +
        "- LFP (Iron Phosphate): Zero Cobalt/Nickel. High Iron content (~800g/kWh). Safer but lower energy density."
    );

    addSection("4. Anomaly Detection Logic",
        "We utilize a Statistical Thresholding approach (3-Sigma Rule).\n" +
        "- The system calculates the 'Expected Degradation' based on mileage.\n" +
        "- If (Actual_Degradation - Expected_Degradation) > 27.0 (Threshold derived from training data variance), an ANOMALTY is flagged.\n" +
        "- This indicates internal faults (e.g., lithium plating, thermal runaway risk) rather than normal wear."
    );

    // Footer
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text("Generated by EV-Insight Pro | Academic Project 2025", 15, 280);

    pdf.save('EV_Battery_Health_Report.pdf');
};
